### ISSUE TITLE
Variable "current_announcement" does not exist in app/Resources/RedmonsterAnnouncementBundle/views/Announcement/announcement.html.twig at line 1

### ISSUE THREAD

**Issue by alexloehner** [redmonster/AnnouncementBundle#4]
Hi there,

I've installed and configured the announcement bundle in my Symfony 2.6.6, I've then copied your "views/Announcements/announcements.html.twig" to "app/Resources/RedmonsterAnnouncementBundle" in order to overload it.

Then I've added  "{{ include('RedmonsterAnnouncementBundle:Announcement:announcement.html.twig') }}" to my base.html.twig.

So quiet normal until now, not?

Then I've created a test announcement through the console command, still without any problems or error.

But then, when browsing to my application, I get this:

Variable "current_announcement" does not exist in app/Resources/RedmonsterAnnouncementBundle/views/Announcement/announcement.html.twig at line 1
500 Internal Server Error - Twig_Error_Runtime

So, the variables are not in a global scope?

What am I missing?

**Comment by paulredmond** [comment]
Sorry I haven't had much time to do further development and documentation. You basically need to embed a controller which is described here in the Symfony docs. I haven't tested this on many Symfony2 versions yet, but should be simple enough I think to get it working.

http://symfony.com/doc/current/book/templating.html#embedding-controllers

**Comment by paulredmond** [comment]
This would be the controller you want to use: https://github.com/redmonster/AnnouncementBundle/blob/master/Controller/AnnouncementController.php

**Comment by alexloehner** [comment]
Okay, thanks that works.
